### ISSUE TITLE
Connection refused when trying to connect to a CardDav Baikal server

### ISSUE THREAD

**Issue by patufet99** [prrvchr/vCardOOo#1]
Hello,

I have installed vCardOOo on a Ubuntu system following the detailed indications without problem. The CardDav server that I use is not a NextCloud server but Baikal (https://github.com/sabre-io/Baikal) running on another linux machine.

I cannot establish a communication from vCardOOo to this Baikal server.
I can access the same Baikal server from other applications (Thunderbird or DavX5).

For the configuration, in the field: DBMS/driver-specific connection I introduce as on the other applications:
https://myserver.com/baikal/html/dav.php/addressbooks/myadresses/default/
and the user name and then the password when requested, but the connection is always refused.

I am doing something wrong? Is there a compatibility problem with the Baïkal server?

Let me know if a log file may be of help.

Thank you.

**Comment by prrvchr** [comment]
Hi,

I confirm a connection problem on my Nextcloud server. This problem seems to be linked to a regression that appeared with version 1.2 of the OAuth2OOo extension.

I made the necessary modifications for a good connection to my Nextcloud server. I'll let you confirm that this also works with your Baikal server.

You must install the two new versions:
- [OAuth2OOo v1.2.3](https://github.com/prrvchr/OAuth2OOo/releases/latest/download/OAuth2OOo.oxt)
- [vCardOOo 1.0.4](https://github.com/prrvchr/vCardOOo/releases/latest/download/vCardOOo.oxt)

**Comment by patufet99** [comment]
Hello,

thank you for your feedback. I seem to have a problem to enable the OAuth2OOo v1.2.3 extension.
I get the following errors:

![Screenshot from 2023-12-16 21-31-33](https://github.com/prrvchr/vCardOOo/assets/14853573/a5359907-b85e-4455-a33d-fe9ad6f6380f)

![Screenshot from 2023-12-16 21-33-53](https://github.com/prrvchr/vCardOOo/assets/14853573/46067a6d-a82f-48f3-b2d1-664e19c57970)

![Screenshot from 2023-12-16 21-33-02](https://github.com/prrvchr/vCardOOo/assets/14853573/81568cb6-96f1-4c20-baae-691964e03d33)


This is the LibreOffice version that I am using on Ubuntu 22.04.

![Screenshot from 2023-12-16 21-33-30](https://github.com/prrvchr/vCardOOo/assets/14853573/c27ec945-7171-4e66-922e-c0336a8e18ad)

**Comment by prrvchr** [comment]
Hi patufet99,

This error corresponds to a python module embedded by the OAuth2OOo extension (here cssselect) which is incorrectly installed or in conflict with the python system version (for LibreOffice on Linux and OSX exclusively because on Windows Python is embedded with LibreOffice).

Two things need to be checked:
- That the system python version is 3.10. And if it is another version then you must install the python binary (but normally under Ubuntu 22.04 and if it has not been updated the python version must be 3.10)
- Uninstalling or reinstalling the extension under LibreOffice does not complete correctly. In this case you must ensure that the uninstallation of the extension is done correctly before wanting to reinstall a new version. To do this, simply observe what happens in the extensions folder when installing and uninstalling an extension. Under Linux the extensions folder is: **~/.config/libreoffice/4/user/uno_packages/cache/uno_packages**. And if the uninstallation goes correctly then after uninstalling an extension, close then re-open LibreOffice and return to the list of installed extensions, then at this time, the extension subdirectory should disappear in the extensions folder. If this is not the case then the user profile will have to be replaced (close LibreOffice, rename ~/.config/libreoffice directory, restart LibreOffice) in order to be sure to leave with correctly installed extensions. Please note, after replacing the LibreOffice profile you will lose all your LibreOffice settings...
​

**Comment by patufet99** [comment]
Thank you for your detailed explanation.
You are right and the problem seems to lie with the installation of the OAuth2OOo extension.

`pere@pere-G10AJ:~/.config$ python --version
Python 3.10.12
`

The Ubuntu python version is 3.10.12

I have tried to completely  reinstall Libreoffice, as well as reset it to factory settings from Safe Mode. In each case when installing the OAuth2OOo extension I keep getting the same error.

**Comment by prrvchr** [comment]
It appears that you already have the parsel and/or cssselect Python packages installed.
Can you confirm me with the command **pip3 show parsel** and **pip3 show cssselect**

**Comment by patufet99** [comment]
I get that on the terminal

![Screenshot from 2023-12-17 15-43-47](https://github.com/prrvchr/vCardOOo/assets/14853573/385d3942-b2fa-4248-9ffb-ae95da94ce04)

**Comment by prrvchr** [comment]
Ok, your **cssselect is outdated** and although the OAuth2OOo extension provides this python package, the system one takes precedence. The correct version for cssselect must be 1.2.0.
Can you try updating with pip (I don't remember the command...)

**Comment by patufet99** [comment]
With your indications the extension is installed correctly.
When testing the connection, it returns, however, an error.

![Screenshot from 2023-12-17 16-17-33](https://github.com/prrvchr/vCardOOo/assets/14853573/c79207e5-a30a-4e81-a9aa-4188cfb7e440)
![Screenshot from 2023-12-17 16-17-03](https://github.com/prrvchr/vCardOOo/assets/14853573/e049ac2c-33d8-4e84-afdd-736cc05a87f6)
![Screenshot from 2023-12-17 16-15-33](https://github.com/prrvchr/vCardOOo/assets/14853573/ae692f65-fcb4-43d9-a058-fe1f52a9a09c)
![Screenshot from 2023-12-17 16-16-26](https://github.com/prrvchr/vCardOOo/assets/14853573/10945b09-43df-4c44-ad6e-be8cc8f01d70)

**Comment by patufet99** [comment]
I'm sorry, the problem was due to the fact, that I had reinstalled LibreOffice and had forgotten to uninstall the
the libhsqldb1.8.0-java package.
Removing this package and installing afterwards the oAuth2OOo Extension I still get this error:

![Screenshot from 2023-12-17 16-38-30](https://github.com/prrvchr/vCardOOo/assets/14853573/23c83a5e-f26d-43a8-8cd8-afacaf66e483)

**Comment by prrvchr** [comment]
If the launch of the extensions fails due to a faulty LibreOffice configuration, then you must correct the LibreOffice configuration and then uninstall all the extensions, ensuring that they have been correctly uninstalled. Then reinstall all extensions.
It's a bit long but it's the only way to be sure that everything is installed correctly.

**Comment by patufet99** [comment]
I haven't changed the Java configuration: by default LibreOffice uses the Ubuntu 11.0.21 version.

/usr/lib/jvm/java-11-openjdk-amd64

I have restarted LibreOffice in safe-mode and reset to factory settings resetting settings and the entire user profile. This should completely remove the extensions. I have then reinstalled the 3 extensions and I get exactly the same error as previously:

SQL Status: HY000
The connection to the external data source could not be established. An unknown error occurred. The driver is probably defective. ./connectivity/source/commontools/dbexception.cxx:413

I don't think this is an installation problem, but maybe I'm doing something wrong.

**Comment by prrvchr** [comment]
I need more information. Can you launch LibreOffice from a terminal, you can see any errors coming from the extension.
Open a terminal and type **soffice** then enter.

**Comment by patufet99** [comment]
I don't seem to get any error

![Screenshot from 2023-12-17 18-37-35](https://github.com/prrvchr/vCardOOo/assets/14853573/3fc360ad-8611-466c-bf7c-6038d4a403eb)

**Comment by prrvchr** [comment]
`SQL Status: HY000`

This error is due to a malfunction of the jdbcDriveOOo extension, you must try to reinstall it after a correct uninstallation (no more folders in the extensions directory)

**Comment by patufet99** [comment]
I have tried to do as you indicate a correct uninstallation, checked that the extension folder is empty, and install again the extensions. I get the same result.

I have launched libreoffice from the command line and try to make a connection. I attach here below what I get ( I have just changed the url of the server, username and password)..

[soffice_log.txt](https://github.com/prrvchr/vCardOOo/files/13697686/soffice_log.txt)

**Comment by prrvchr** [comment]
Hi patufet99,

So I just updated **vCardOOo to version 1.1.1** which fixes your latest bug and which should allow any errors occurring in HTTP requests to be logged.

The connection URL to give is the name of the server on the Internet, (ie: nuage.distrilab.fr)
- `https://` is not necessary and will be added if it is not present.
- `http://` is only necessary to force an unencrypted connection.

And thank you for making it possible to improve operation on a Baikal server...

**Comment by prrvchr** [comment]
`SQL Status: HY000`  must be an error which comes from a missing package in the installation of LibreOffice, package which must be necessary for the connection to the database...

Without further information I close...
